### ISSUE TITLE
Recommended additions to the .kitchen.yml for AWS

### ISSUE THREAD

**Issue by irvingpop** [jeremiahsnapp/dev-lxc-platform#7]
Found a couple of minor things that should be added to the .kitchen.yml to make life easier for Chef folks:

1.  Specify a region -  it defaults to us-west-1 but you need the region and keypair to match, so better to call it out explicitly so folks know what to change

under the `driver` key:
```
      region: us-west-1
```

2.  Provide example tags so that instances don't get reaped (and get cost accounted appropriately)

under the `driver` key:
```
      tags:
        created-by: test-kitchen
        Name: dev-lxc-platform
        X-Contact: myname
        X-Dept: mydepartment
```

**Comment by jeremiahsnapp** [comment]
Great idea. Thanks @irvingpop. I just added those in 9.1.1.

https://github.com/jeremiahsnapp/dev-lxc-platform/blob/master/CHANGELOG.md#911-2017-02-28
